name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18,20,22 ]
      fail-fast: false        
  
    steps:
      -uses: actions/checkout@v4
      -name: Setup Node Js ${{matrix.node-version}}
       uses: actions/setup-node@v3
       with:
         node-version: ${{matrix.node-version}}
         cache: 'npm'
      -run: npm ci
      -run: npm test